services:
  mock-datasource:
    build: .
    container_name: mock-datasource-srv
    restart: unless-stopped
    env_file: .env
    ports:
      - "${APP_PORT:-8087}:8087"
    volumes:
      # Mount thư mục Csv_v2 để gen service đọc schema
      - ../../GenSchemaDev/Schemas/Csv_v2:/schemas:ro
    environment:
      SCHEMA_DIR: /schemas
    networks:
      - dmst_thcs-net

networks:
  dmst_thcs-net:
    external: true
