services:
  thcs-admin-service:
    container_name: thcs-admin-service
    image: ${IMAGE_THCS_ADMIN_SERVICE:-thcs-admin-service:latest}
    build:
      context: ../../src/services/admin-service
      dockerfile: ../../../deploy/docker/admin-service/Dockerfile

    restart: unless-stopped
    env_file:
      - .env.admin-service
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - thcs-net
      - local-net
      - integration_network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  thcs-net:
    external: true
    driver: bridge
    name: thcs-net
  local-net:
    name: cts_dev_network
    external: true
  integration_network:
    name: dmst_integration_network
    external: true
