services:
  dmst-mock-datasource:
    container_name: dmst-mock-datasource
    image: ${IMAGE_MOCKDS:-dmst-mock-datasource:latest}

    restart: unless-stopped
    env_file:
      - .env.mock-datasource
    ports:
      - "${APP_PORT:-8087}:8087"
    networks:
      - thcs-net
      - local-net
      - integration_network
      - dmst-thcs-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8087/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  thcs-net:
    external: true
    name: thcs-net
  local-net:
    external: true
    name: cts_dev_network
  integration_network:
    external: true
    name: dmst_integration_network
  dmst-thcs-network:
    external: true
    name: dmst_thcs_network
