services:
  portal-spa:
    # image: 10.60.129.132:8890/cmp/portal-spa:latest
    image: ${IMAGE_THCS_PORTAL_SPA:-thcs-portal-spa:latest}
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portal-spa
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped
