# Generic Stream Processor Configuration - DEV

metadata.id=ttdlqg-template

# Kafka Configuration
kafka.brokers=localhost:9092
kafka.source.topic.pattern=TH_TTDLQG_.*
kafka.starting.offset=latest
kafka.partition.discovery.interval.ms=30000
kafka.cdp.brokers=160.191.32.149:9092
kafka.cdp.metadata.topic.partitions=3
kafka.cdp.metadata.topic.replication.factor=1
kafka.file.request.topic.partitions=3
kafka.file.request.topic.replication.factor=1

# PostgreSQL Database Configuration
db.host=postgres-db
db.port=5432
db.name=DMST_Integration_DB
db.user=postgres
db.password=Abcd@123456

# Flink Configuration
parallelism=2
checkpoint.interval=60000
state.backend=rocksdb

# OpenTelemetry
otel.endpoint=
otel.service.name=flink-ttdlqg-generic-stream-processor
